export enum AppAbility {
  DASHBOARD_VIEW = "dashboard:view",
  TABLES_VIEW = "tables:view",
  TABLES_MANAGE = "tables:manage",
  RESERVATIONS_VIEW = "reservations:view",
  RESERVATIONS_MANAGE = "reservations:manage",
  CUSTOMERS_VIEW = "customers:view",
  CUSTOMERS_MANAGE = "customers:manage",
  EMPLOYEES_VIEW = "employees:view",
  EMPLOYEES_MANAGE = "employees:manage",
  SHIFTS_VIEW = "shifts:view",
  SHIFTS_MANAGE = "shifts:manage",
  PAYROLL_VIEW = "payroll:view",
  PAYROLL_MANAGE = "payroll:manage",
  MENU_CATEGORY_VIEW = "menu-category:view",
  MENU_CATEGORY_MANAGE = "menu-category:manage",
  DISH_VIEW = "dishes:view",
  DISH_MANAGE = "dishes:manage",
  MENU_VIEW = "menu:view",
  MENU_MANAGE = "menu:manage",
  ORDER_VIEW = "orders:view",
  ORDER_MANAGE = "orders:manage",
  ORDER_ITEM_VIEW = "order-items:view",
  ORDER_ITEM_MANAGE = "order-items:manage",

  INGREDIENTS_VIEW = "ingredients:view",
  INGREDIENTS_MANAGE = "ingredients:manage",
  SUPPLIERS_VIEW = "suppliers:view",
  SUPPLIERS_MANAGE = "suppliers:manage",
  WAREHOUSE_IMPORT_VIEW = "warehouse-import:view",
  WAREHOUSE_IMPORT_MANAGE = "warehouse-import:manage",
  WAREHOUSE_EXPORT_VIEW = "warehouse-export:view",
  WAREHOUSE_EXPORT_MANAGE = "warehouse-export:manage",
  WAREHOUSE_LOSS_VIEW = "warehouse-loss:view",
  WAREHOUSE_LOSS_MANAGE = "warehouse-loss:manage",
  INVOICES_VIEW = "invoices:view",
  INVOICES_MANAGE = "invoices:manage",
  PROMOTIONS_VIEW = "promotions:view",
  PROMOTIONS_MANAGE = "promotions:manage",
  ROLES_VIEW = "roles:view",
  ROLES_MANAGE = "roles:manage",
  PERMISSION_MATRIX_VIEW = "permission-matrix:view",
  PERMISSION_MATRIX_MANAGE = "permission-matrix:manage"
}

export const ALL_ABILITIES = Object.values(AppAbility)
